# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shots_number', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1)),
                ('water', models.FloatField(blank=True, default='', null=True)),
                ('milk', models.BooleanField(default=False)),
                ('foam', models.FloatField(blank=True, default='', null=True)),
                ('extra_instructions', models.TextField(blank=True, default='', null=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powder_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syrup_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='bean_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabica.CoffeeBean'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='powder_type',
            field=models.ManyToManyField(to='arabica.Powder'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabica.Roast'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='syrup_type',
            field=models.ManyToManyField(to='arabica.Syrup'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
