# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt', models.CharField(choices=[('Arabica', 'Arabica'), ('Robusta', 'Robusta')], default=('Arabica', 'Arabica'), max_length=7)),
                ('cbt_price', models.FloatField()),
            ],
        ),
    ]
