# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0002_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arabica.City'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='shots_number',
            field=models.PositiveIntegerField(),
        ),
    ]
