# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0002_bean'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt', models.CharField(choices=[('ARABICA', 'Arabica'), ('ROBUSTA', 'Robusta')], default='ARABICA', max_length=20)),
                ('cbt_price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bean',
        ),
    ]
