# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0003_auto_20170816_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeebean',
            old_name='cbt_price',
            new_name='bean_price',
        ),
        migrations.RenameField(
            model_name='coffeebean',
            old_name='cbt',
            new_name='coffee_bean',
        ),
    ]
