# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 17:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0004_auto_20170821_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='shots_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
