# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arabica', '0005_auto_20170816_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shots_number', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1)),
                ('water', models.FloatField()),
                ('milk', models.BooleanField(default=False)),
                ('foam', models.FloatField()),
                ('extra_instructions', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('completed', models.DateTimeField(auto_now_add=True)),
                ('bean_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabica.CoffeeBean')),
                ('powder_type', models.ManyToManyField(to='arabica.Powder')),
                ('roast_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabica.Roast')),
                ('syrup_type', models.ManyToManyField(to='arabica.Syrup')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
