# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0006_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
