# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0007_auto_20170817_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='extra_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='foam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='water',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
