# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0008_auto_20170819_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='extra_instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='foam',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='water',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
