# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170823_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='name',
        ),
    ]
