# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170824_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='name',
            new_name='cart',
        ),
    ]
