# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20170824_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=6),
        ),
    ]
