# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arabica', '0006_order'),
        ('cart', '0009_auto_20170824_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='cart.CartItem', to='arabica.Coffee'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='arabica.Coffee'),
            preserve_default=False,
        ),
    ]
